### ISSUE TITLE
How I can get existing models in Anki? 

### ISSUE THREAD

**Issue by Horhik** [is343/react-native-ankidroid#10]
I found, how I can create and use new model, but how I can select existing model and use addNote method for it? Either this functional still unavailable?

**Comment by is343** [comment]
You can get a list of existing models with`getModelList`.  This will give model ids and names.
Then get the model fields of the model with `getFieldList` using either an id or name.
Then, when creating a class instance of AnkiDroid and when calling `addNote`, use the target model and modelFields info to create for an already existing model. 

The model fields must match exactly, or the native AnkiDroid api will return an error.

**Comment by Horhik** [comment]
It works! Thank you
