### ISSUE TITLE
When will the media upload fixes released?

### ISSUE THREAD

**Issue by InfiniteRain** [is343/react-native-ankidroid#31]
Hey, a few months ago I submitted a PR that fixed some issues with my original implementation of media upload. I see that this hasn't been released yet. Is there an ETA?

**Comment by is343** [comment]
Oh hey! Sorry about that! I thought I had already released it, but you are right, it looks like I forgot to do the npm release.  

I am out of town until Thursday of this week. I will run the release commands once I'm back on Thursday. 

Sorry again!
